=== superowner/Shiny-ID3-Tagger/Shiny ID3 Tagger/config/schemas/accounts.default.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-06/schema#",
	"$id": "https://github.com/ShinyId3Tagger/Shiny-ID3-Tagger/accounts.default.json",
	"type": "object",
	"properties": {
		"GitHub": {
			"type": "object",
			"properties": {
				"AccessToken": {
					"type": "string"
				}
			},
			"required": [
				"AccessToken"
			]
		},
		"7digital": {
			"type": "object",
			"properties": {
				"key": {
					"type": "string"
				}
			},
			"required": [
				"key"
			]
		},
		"Amazon": {
			"type": "object",
			"properties": {
				"AssociateTag": {
					"type": "string"
				},
				"AccessKey": {
					"type": "string"
				},
				"SecretKey": {
					"type": "string"
				}
			},
			"required": [
				"AssociateTag",
				"AccessKey",
				"SecretKey"
			]
		},
		"Apiseeds": {
			"type": "object",
			"properties": {
				"ApiKey": {
					"type": "string"
				}
			},
			"required": [
				"ApiKey"
			]
		},
		"Decibel": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"AppId": {
						"type": "string"
					},
					"AppKey": {
						"type": "string"
					}
				},
				"required": [
					"AppId",
					"AppKey"
				]
			}
		},
		"Discogs": {
			"type": "object",
			"properties": {
				"Key": {
					"type": "string"
				},
				"Secret": {
					"type": "string"
				}
			},
			"required": [
				"Key",
				"Secret"
			]
		},
		"Genius": {
			"type": "object",
			"properties": {
				"AccessToken": {
					"type": "string"
				}
			},
			"required": [
				"AccessToken"
			]
		},
		"Gracenote": {
			"type": "object",
			"properties": {
				"ClientId": {
					"type": "string"
				},
				"UserId": {
					"type": "string"
				}
			},
			"required": [
				"ClientId",
				"UserId"
			]
		},
		"Lastfm": {
			"type": "object",
			"properties": {
				"ApiKey": {
					"type": "string"
				}
			},
			"required": [
				"ApiKey"
			]
		},
		"MusicGraph": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"AppKey": {
						"type": "string"
					}
				},
				"required": [
					"AppKey"
				]
			}
		},
		"Musixmatch": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"type": "object",
				"properties": {
					"ApiKey": {
						"type": "string"
					}
				},
				"required": [
					"ApiKey"
				]
			}
		},
		"MsGroove": {
			"type": "object",
			"properties": {
				"ClientId": {
					"type": "string"
				},
				"ClientSecret": {
					"type": "string"
				}
			},
			"required": [
				"ClientId",
				"ClientSecret"
			]
		},
		"Napster": {
			"type": "object",
			"properties": {
				"ApiKey": {
					"type": "string"
				}
			},
			"required": [
				"ApiKey"
			]
		},
		"Qobuz": {
			"type": "object",
			"properties": {
				"AppId": {
					"type": "string"
				}
			},
			"required": [
				"AppId"
			]
		},
		"Spotify": {
			"type": "object",
			"properties": {
				"ClientId": {
					"type": "string"
				},
				"ClientSecret": {
					"type": "string"
				}
			},
			"required": [
				"ClientId",
				"ClientSecret"
			]
		},
		"Tidal": {
			"type": "object",
			"properties": {
				"Username": {
					"type": "string"
				},
				"Password": {
					"type": "string"
				},
				"Token": {
					"type": "string"
				}
			},
			"required": [
				"Username",
				"Password",
				"Token"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"GitHub",
		"7digital",
		"Amazon",
		"Apiseeds",
		"Decibel",
		"Discogs",
		"Genius",
		"Gracenote",
		"Lastfm",
		"Musixmatch",
		"Napster",
		"Qobuz",
		"Spotify",
		"Tidal"
	]
}

=== superowner/Shiny-ID3-Tagger/Shiny ID3 Tagger/config/accounts.user.json
{
	"GitHub": {
		"AccessToken": ""
	},
	"7digital": {
		"key": ""
	},
	"Amazon": {
		"AssociateTag": "",
		"AccessKey": "",
		"SecretKey": ""
	},
	"Apiseeds": {
		"ApiKey": ""
	},
	"Decibel": [
		{
			"AppId": "",
			"AppKey": ""
		}
	],
	"Discogs": {
		"Key": "",
		"Secret": ""
	},
	"Genius": {
		"AccessToken": ""
	},
	"Gracenote": {
		"ClientId": "",
		"UserId": ""
	},
	"Lastfm": {
		"ApiKey": ""
	},
	"Musixmatch": [
		{
			"ApiKey": ""
		}
	],
	"Napster": {
		"ApiKey": ""
	},
	"Qobuz": {
		"AppId": ""
	},
	"Spotify": {
		"ClientId": "",
		"ClientSecret": ""
	},
	"Tidal": {
		"Username": "",
		"Password": "",
		"Token": ""
	}
}

=== superowner/Shiny-ID3-Tagger/Shiny ID3 Tagger/config/accounts_sample.json
{
	"GitHub": {
		"AccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"7digital": {
		"key": "xxxxxxxxxxxx"
	},
	"Amazon": {
		"AssociateTag": "example-tag",
		"AccessKey": "xxxxxxxxxxxxxxxxxxxx",
		"SecretKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Apiseeds": {
		"ApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Decibel": [
		{
			"AppId": "xxxxxxxx",
			"AppKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}
	],
	"Discogs": {
		"Key": "xxxxxxxxxxxxxxxxxxxx",
		"Secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Genius": {
		"AccessToken": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Gracenote": {
		"ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"UserId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Lastfm": {
		"ApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Musixmatch": [
		{
			"ApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}
	],
	"Napster": {
		"ApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Qobuz": {
		"AppId": "xxxxxxxxx"
	},
	"Spotify": {
		"ClientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
		"ClientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"Tidal": {
		"Username": "mail@example.com",
		"Password": "xxxxxxxxxxxxxxxxxxxx",
		"Token": "xxxxxxxxxxxxxxxx"
	}
}
